eclipse-emfcloud/emfcloud-modelserver

- README.md
- org.eclipse.emfcloud.modelserver.client/src/main/java/org/eclipse/emfcloud/modelserver/client/ModelServerClient.java
- org.eclipse.emfcloud.modelserver.client/src/main/java/org/eclipse/emfcloud/modelserver/client/ModelServerClientApiV1.java
- org.eclipse.emfcloud.modelserver.client/src/test/java/org/eclipse/emfcloud/modelserver/client/ModelServerClientTest.java
I have implemented the create call implementation on the client.
To prevent duplicate code I did some refactoring in ModelServerClient to combine update and create, as these are nearly the same.
> Fix #9 Client should support create call

- org.eclipse.emfcloud.modelserver.emf/src/main/java/org/eclipse/emfcloud/modelserver/emf/configuration/ServerConfiguration.java
- org.eclipse.emfcloud.modelserver.emf/src/test/java/org/eclipse/emfcloud/modelserver/emf/configuration/ServerConfigurationTest.java
If using a workspace which includes spaces or other encoded chars the
ModelServer doesn't recognize the workspace and doesn't set it.
Signed-off-by: Eugen Neufeld <eneufeld@eclipsesource.com>
> Fix normalization of encoded workspace URLs

- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/ModelRepository.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/launch/CLIParser.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/launch/ModelServerLauncher.java
- examples/org.eclipse.emfcloud.modelserver.example/src/main/java/org/eclipse/emfcloud/modelserver/example/ExampleServerLauncher.java
- Add static configuration method for logger
- Move generic CLIParserHandling from example to base launcher class
- Enable launching the modelsever without a valid modelsever root (can be passed later at runtime e.g. from theia)
> Improve ModelServerLauncher

- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/configuration/ServerConfiguration.java
By using the toFileString() method, the returned string was not usable on windows as it was transformed from `c:/foo` to `c:%5Cfoo` as backslashes must be encoded.
By using the toString() method we return a valid path
> Update ServerConfiguration path

- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/ServerController.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/configuration/ServerConfiguration.java
- tests/org.eclipse.emfcloud.modelserver.emf.tests/src/org/eclipse/emfcloud/modelserver/emf/configuration/ServerConfigurationTest.java
* Remove ServerConfiguration#getWorkspaceRoot() method
* Change all users to ServerConfiguration#getWorkspaceRootURI()
Signed-off-by: Eugen Neufeld <eneufeld@eclipsesource.com>
> Fix Path handling for Windows

- README.md
- bundles/org.eclipse.emfcloud.modelserver.client/src/org/eclipse/emfcloud/modelserver/client/ModelServerClient.java
- bundles/org.eclipse.emfcloud.modelserver.client/src/org/eclipse/emfcloud/modelserver/client/ModelServerClientApiV1.java
- bundles/org.eclipse.emfcloud.modelserver.client/src/org/eclipse/emfcloud/modelserver/client/ServerConfiguration.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/ModelRepository.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/ModelServerRouting.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/SchemaController.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/SchemaRepository.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/ServerController.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/configuration/ServerConfiguration.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/launch/CLIParser.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/launch/ModelServerLauncher.java
- examples/org.eclipse.emfcloud.modelserver.example/src/main/java/org/eclipse/emfcloud/modelserver/example/ExampleServerLauncher.java
- tests/org.eclipse.emfcloud.modelserver.client.tests/src/org/eclipse/emfcloud/modelserver/client/ModelServerClientTest.java
- tests/org.eclipse.emfcloud.modelserver.emf.tests/src/org/eclipse/emfcloud/modelserver/emf/common/SchemaControllerTest.java
- tests/org.eclipse.emfcloud.modelserver.emf.tests/src/org/eclipse/emfcloud/modelserver/emf/common/SchemaRepositoryTest.java
- tests/org.eclipse.emfcloud.modelserver.emf.tests/src/org/eclipse/emfcloud/modelserver/emf/configuration/ServerConfigurationTest.java
- Make sure the UI schema directory is part of the server configuration
- Skip UI schema directory resources when loading workspace resources
- Guard against NPE by checking resource content in 'getAllModels'
Signed-off-by: Martin Fleck <mfleck@eclipsesource.com>
> Fix #45: Ensure UI Schema directory is skipped when scanning workspace

- bundles/org.eclipse.emfcloud.modelserver.lib/.classpath
- bundles/org.eclipse.emfcloud.modelserver.lib/META-INF/MANIFEST.MF
- bundles/org.eclipse.emfcloud.modelserver.lib/build.properties
- releng/org.eclipse.emfcloud.modelserver.releng.target/r2019-12.target
- releng/org.eclipse.emfcloud.modelserver.releng.target/r2019-12.tpd
When trying to use the org.eclipse.emfcloud.modelserver.lib as a bundle,
the libraries inside the bundle can't resolve necessary dependencies, eg
slf4j.
By adding the dependencies explicitly to the MANIFEST, this issue is
resolved.
Signed-off-by: Eugen Neufeld <eneufeld@eclipsesource.com>
> Add necessary dependencies to modelserver.lib bundle

- pom.xml
- This plug-in repackages some external Jars, and doesn't actually provide any source code
Note: the PR build doesn't include the update site; so we missed this issue in the previous PR (#47). To test this, we need to run the build with:
`mvn clean verify -Pp2 -Pp2-release`
And check that `org.eclipse.emfcloud.modelserver.releng.p2` is succesfully built:
```
[INFO] org.eclipse.emfcloud.modelserver.feature ........... SUCCESS [  0.179 s]
[INFO] org.eclipse.emfcloud.modelserver.releng.p2 ......... SUCCESS [01:33 min]
```
> Ignore org.eclipse.emfcloud.modelserver.lib for source-feature

- README.md
- bundles/org.eclipse.emfcloud.modelserver.client/src/org/eclipse/emfcloud/modelserver/client/ModelServerClient.java
- bundles/org.eclipse.emfcloud.modelserver.client/src/org/eclipse/emfcloud/modelserver/client/ModelServerClientApiV1.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/JsonResponse.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/JsonResponseType.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/ModelServerRouting.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/SessionController.java
- tests/org.eclipse.emfcloud.modelserver.emf.tests/src/org/eclipse/emfcloud/modelserver/emf/common/SessionControllerTest.java
- Allow clients to set idle timeout on subscription (default is 300000ms)
- Handle ws messages (type keepAlive) to enable clients to prolong connection independently
- Extend SessionControllerTest
- Remove TestOnly predicate in SessionController and mock fields directly
- Remove format argument in subscribe(..) in ModelServerClientAPI as it was never used or implemented (may open an issue for that though)
Signed-off-by: Nina Doschek <ndoschek@eclipsesource.com>
Please also see https://github.com/eclipse-emfcloud/emfcloud-modelserver-theia/pull/23
> Improve WebSocket connections regarding timeout and keepAlive messages

- bundles/org.eclipse.emfcloud.modelserver.client/src/org/eclipse/emfcloud/modelserver/client/ModelServerClient.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/ModelController.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/SessionController.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/codecs/Codecs.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/codecs/CodecsManager.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/di/DefaultModelServerModule.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/di/ModelServerModule.java
- tests/org.eclipse.emfcloud.modelserver.emf.tests/src/org/eclipse/emfcloud/modelserver/emf/common/ModelControllerTest.java
- tests/org.eclipse.emfcloud.modelserver.emf.tests/src/org/eclipse/emfcloud/modelserver/emf/common/SessionControllerTest.java
Use Map binding for codecs and format. Also give the possibility to
specify a preferred format (json by default).
The Model Server Client now has overrideable methods so that it can
change the accepteable formats when necessary.
Signed-off-by: vhemery <vincent.hemery@csgroup.eu>
> Improve extensibility of model server formats and codecs #60

- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/DefaultModelResourceManager.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/ModelController.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/ModelRepository.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/ModelResourceManager.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/ModelServerEditingDomain.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/SessionController.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/codecs/Codecs.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/codecs/CodecsManager.java
- Ensure undo/redo commands can be encoded to broadcast to all listeners
- Especially for XMI listeners it is therefore necessary to encode the commands before actual undo/redo as the encoding using the already changed resource leads cannot be completed.
Signed-off-by: Nina Doschek <ndoschek@eclipsesource.com>
> Fix broadcasting of Undo/Redo updates especially for XMI listeners

- bundles/org.eclipse.emfcloud.modelserver.lib/pom.xml
- pom.xml
- Create empty jar for *.lib as otherwise gpg has nothing to sign
Signed-off-by: Martin Fleck <mfleck@eclipsesource.com>
> Fix #62: Fix m2-release by creating empty jar for *.lib project

- README.md
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/DefaultModelResourceManager.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/ModelServerRouting.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/ServerController.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/di/DefaultModelServerModule.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/di/ModelServerModule.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/launch/ModelServerLauncher.java
- Fixes #71: Process incoming requests after server configuration is completed
- Make ModelServerRouting configurable via DI
- Enhance logging of request routing
- Change some log lines to debug level
- Change default debug level to DEBUG
- Fixes #72: Absolute full path as modelURI causes error
Signed-off-by: Nina Doschek <ndoschek@eclipsesource.com>
> Process incoming requests after server configuration is completed

- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/ModelServerRouting.java
Add correct json response for server configuration request
Signed-off-by: Nina Doschek <ndoschek@eclipsesource.com>
> Fix #75 Request server/configure does not deliver JsonResponse

- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/DefaultModelResourceManager.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/ModelResourceManager.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/ModelServerRouting.java
Fixing absolute file URI with device for windows.
Moving the adaptModelUri method to ModelResourceManager.
> Absolute full path as modelURI causes error #72

- bundles/org.eclipse.emfcloud.modelserver.edit/plugin.xml
- bundles/org.eclipse.emfcloud.modelserver.edit/resources/Command.ecore
- bundles/org.eclipse.emfcloud.modelserver.edit/src-gen/org/eclipse/emfcloud/modelserver/command/CCommandPackage.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/DefaultModelResourceManager.java
- tests/org.eclipse.emfcloud.modelserver.edit.tests/resources/Command.xmi
- tests/org.eclipse.emfcloud.modelserver.emf.tests/src/org/eclipse/emfcloud/modelserver/emf/common/DefaultSessionControllerTest.java
- Use http://www.eclipse.org/emfcloud/modelserver/command as NS URI
- Adapt URI where necessary
Signed-off-by: Martin Fleck <mfleck@eclipsesource.com>
> Fix #87: Adapt command package namespace URI to better reflect source

- .github/workflows/build.yml
- Add ubuntu-latest to Github Actions runners
- Disable MacOS 10.15. (macOS-latest) temporarily for m2 build in GitHub Actions
- MacOS 11.0 is not available publicly yet (see https://docs.github.com/en/actions/using-github-hosted-runners/about-github-hosted-runners#supported-runners-and-hardware-resources)
> #108 Disable macOS 10.15 runner for build-m2 action temporarily

- bundles/org.eclipse.emfcloud.modelserver.client/META-INF/MANIFEST.MF
- bundles/org.eclipse.emfcloud.modelserver.client/src/org/eclipse/emfcloud/modelserver/client/ModelServerClient.java
- bundles/org.eclipse.emfcloud.modelserver.client/src/org/eclipse/emfcloud/modelserver/client/TypedSubscriptionListener.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/DefaultModelResourceManager.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/RecordingModelResourceManager.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/configuration/ChangePackageConfiguration.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/configuration/EPackageConfiguration.java
- examples/org.eclipse.emfcloud.modelserver.example/src/main/java/org/eclipse/emfcloud/modelserver/example/client/ExampleModelServerClient.java
Logging:
We want to to log errors and failures by default to prevent those
problems from being swallowed up since they may contain important
information about underlying issues.
EPackageConfigurations:
Centralize EPackageConfiguration management and apply it on the Java
model server client to ensure proper setup. We also ensure that the
ChangePackage is properly initialized on the client-side. We already use
the RecordingModelResourceManager as default on the server so we need
the ChangePackage to be initialized.
> Fix #111: Add error/failure logging and centralize package configs

- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/RecordingModelResourceManager.java
To ensure the changeDescription object is not null, do not reuse the TransactionChangeRecorder, but create a ChangeRecorder and ensure it is disposed to avoid leftover adapters
> #123 Ensure ChangeRecorder is disposed

- bundles/org.eclipse.emfcloud.modelserver.emf/META-INF/MANIFEST.MF
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/DefaultModelResourceManager.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/ModelResourceManager.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/RecordingModelResourceManager.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/watchers/AbstractModelWatcher.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/watchers/DIModelWatchersManager.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/watchers/FileModelWatcher.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/watchers/ModelWatcher.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/watchers/ModelWatchersManager.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/watchers/ReconcilingStrategy.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/di/DefaultModelServerModule.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/di/MultiBindingDefaults.java
- releng/org.eclipse.emfcloud.modelserver.releng.target/targetplatform.target
- releng/org.eclipse.emfcloud.modelserver.releng.target/targetplatform.tpd
- tests/org.eclipse.emfcloud.modelserver.emf.tests/src/org/eclipse/emfcloud/modelserver/emf/DefaultModelResourceManagerTest.java
- tests/org.eclipse.emfcloud.modelserver.emf.tests/src/org/eclipse/emfcloud/modelserver/emf/common/watchers/FileModelWatcherIntegrationTest.java
Adding ModelWatchers, which must invoked by ModelResourceManager after
loading a resource.
On a divergence, a ModelWatcher must ask the active ReconcilingStrategy
to solve the issue. (2 are contributed)
The default FileModelWatcher implementation is contributed, listening at
file changes, but other implementations are possible for different
protocols.
Fixes #115
> #115 : Introduce file watching concept

- bundles/org.eclipse.emfcloud.modelserver.client/src/org/eclipse/emfcloud/modelserver/client/ModelServerClient.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/SingleThreadModelController.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/di/DefaultModelServerModule.java
Introduce a new ModelController, that handles all incoming requests in the same thread, and delegates the actual behavior to an existing implementation of a ModelController.
This is a simple (and naive) way of ensuring thread-safety. For more complex use cases, we may want to use per-resource set threads instead, or even rely on EMF Transactions (To support single-write, concurrent-read access); but having basic support is probably good enough for now.
This approach is probably less disruptive than modifying the default ModelController, as we should be able to swap the delegate to any existing implementation of a ModelController. It **should** be transparent for existing modules as well (Provided they extend the `DefaultModelServerModule`), but clients should still double-check if the 2 …
> #135 Introduce Thread-Safe ModelController

- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/DefaultUriHelper.java
- tests/org.eclipse.emfcloud.modelserver.emf.tests/src/org/eclipse/emfcloud/modelserver/emf/configuration/DefaultServerConfigurationTest.java
Updating the configuration via the `server/configure` endpoint does not work under Windows when used in combination with Modelserver Theia.
An absolute Windows path typically contains a driver letter followed by a : (e.g c://my-workspace). So when passing absolute paths as URL parameters the `:` need to be encoded.
This means we have to make sure that they are properly decoded on the server side.
The easiest common point to this this the `DefaultUriHelper` class.
Fixes #47
> #47 Workspace configuration not working in Windows

- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/DefaultModelResourceManager.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/DefaultSessionController.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/DefaultTransactionController.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/ModelServerEditingDomain.java
- undo stack was not getting an undoable command when all edits in a transaction were JSON patches
- add support for undo/redo (and execution results) of commands generated from JSON patches that do not have client commands
- do not perform live validation of the model if there are no listeners interested in it
> Undo/redo with JSON patches

- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/DefaultModelController.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/DefaultSessionController.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/DefaultTransactionController.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/ModelController.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/ModelListener.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/util/JsonPatchHelper.java
- tests/org.eclipse.emfcloud.modelserver.emf.tests/resources/.gitignore
- tests/org.eclipse.emfcloud.modelserver.emf.tests/src/org/eclipse/emfcloud/modelserver/emf/common/DefaultModelControllerTest.java
- ensure that v2 subscribers get JSON Patch delta notifications on undo/redo
- unify v1 and v2 incremental change notification so that both v1 and v2 subscribers get deltas of their flavour from command or patch execute/undo/redo (in the case of JSON Patches v1 subscribers don't get a source command)
- defer calculation of JSON Patch delta so that it won't be computed if it is not needed
> #150: Delta patch notifications on undo/redo

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/config.yml
- .github/ISSUE_TEMPLATE/feature_request.md
The issue templates for bugs and feature requests automatically apply the `modelserver` label to new issues.
> #163 Add issue templates to the repository

- bundles/org.eclipse.emfcloud.modelserver.client/src/org/eclipse/emfcloud/modelserver/client/ModelServerClient.java
- bundles/org.eclipse.emfcloud.modelserver.client/src/org/eclipse/emfcloud/modelserver/client/v1/ModelServerClientV1.java
- bundles/org.eclipse.emfcloud.modelserver.client/src/org/eclipse/emfcloud/modelserver/client/v2/ModelServerClientV2.java
- bundles/org.eclipse.emfcloud.modelserver.client/src/org/eclipse/emfcloud/modelserver/internal/client/EditingContextImpl.java
- bundles/org.eclipse.emfcloud.modelserver.client/src/org/eclipse/emfcloud/modelserver/internal/client/ModelServerClientDelegate.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/ModelServerRoutingDelegate.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/ModelServerRoutingV1.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/ModelServerRoutingV2.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/codecs/JsonCodecV2.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/patch/PatchCommandHandler.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/util/JsonPatchHelper.java
- examples/org.eclipse.emfcloud.modelserver.example/src/main/java/org/eclipse/emfcloud/modelserver/example/client/ExampleModelServerClient.java
Split implementations of v1 and v2 APIs via delegation to a common partial implementation instead of inheritance of a common partial implementation in
- the `ModelServerClient` API
- the `ModelServerRouting` handlers
The previously existing abstract base classes are deleted (actually, more or less renamed and moved) instead of deprecated because they were only actually introduced during this release in PR #151, so there is no concern about breaking API for downstream applications.
Fixes #168.
> API v2: Prefer delegation over inheritance

- bundles/org.eclipse.emfcloud.modelserver.common/src/org/eclipse/emfcloud/modelserver/common/patch/AbstractJsonPatchHelper.java
Make the JsonPatchHelper.SettingValue class static instead of final, so clients can extend it.
Contributed on behalf of STMicroelectronics
Fixes #180
> API V2: Open the SettingValue API

- bundles/org.eclipse.emfcloud.modelserver.client/src/org/eclipse/emfcloud/modelserver/client/ModelServerClient.java
- bundles/org.eclipse.emfcloud.modelserver.client/src/org/eclipse/emfcloud/modelserver/client/v1/ModelServerClientV1.java
- bundles/org.eclipse.emfcloud.modelserver.client/src/org/eclipse/emfcloud/modelserver/client/v2/ModelServerClientV2.java
- bundles/org.eclipse.emfcloud.modelserver.client/src/org/eclipse/emfcloud/modelserver/internal/client/ModelServerClientDelegate.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/ModelServerRoutingDelegate.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/ModelServerRoutingV1.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/ModelServerRoutingV2.java
- include the codecs that implement the supported formats in the client API
- add protected delegation APIs in public client and routing classes for continuity of access to APIs that existing clients rely on
> #184 Improve backward API compability

- bundles/org.eclipse.emfcloud.modelserver.common/src/org/eclipse/emfcloud/modelserver/common/codecs/Codec.java
- bundles/org.eclipse.emfcloud.modelserver.common/src/org/eclipse/emfcloud/modelserver/common/codecs/DefaultJsonCodec.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/DefaultModelResourceManager.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/DefaultTransactionController.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/RecordingModelResourceManager.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/util/JsonPatchHelper.java
- tests/org.eclipse.emfcloud.modelserver.emf.tests/src/org/eclipse/emfcloud/modelserver/emf/DefaultModelResourceManagerTest.java
- tests/org.eclipse.emfcloud.modelserver.emf.tests/src/org/eclipse/emfcloud/modelserver/emf/common/watchers/FileModelWatcherIntegrationTest.java
Inject the `JsonPatchHelper` also into the resource manager and transaction controller that previously constructed it for themselves.
This requires additionally:
- provider injection for the resource manager because the patch helper depends on the resource manager
- configuration of injectors in tests now needs to include injection of codecs map because it is injected into the patch helper
So far, this is tied to `json-v2` format exclusively as this is the default format for API v2. If the helper should need to pick up other formats from the request/socket context, then that's an orthogonal issue.
> Fix #174 API v2: Injection of JsonPatchHelper

- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/DefaultModelURIConverter.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/ModelServerRoutingDelegate.java
- tests/org.eclipse.emfcloud.modelserver.emf.tests/src/org/eclipse/emfcloud/modelserver/emf/common/DefaultModelURIConverterTest.java
- tests/org.eclipse.emfcloud.modelserver.emf.tests/src/org/eclipse/emfcloud/modelserver/emf/common/ModelServerRoutingV2Test.java
- delete empty authorities from incoming `file`-scheme model URIs
- double-check existence of the `modeluri` query param when delegating a `GET /models` request to `ModelController::getAll(Context)`
> Fix #188: URI Converter problems

- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/util/JsonPatchHelper.java
- tests/org.eclipse.emfcloud.modelserver.emf.tests/src/org/eclipse/emfcloud/modelserver/emf/common/watchers/FileModelWatcherIntegrationTest.java
- Normalize URIs in ~DefaultModelResourceManager~ and JsonPatchHelper
fixes #193
> 193: JsonPatchHelper should normalize URIs when using EMF-style paths

- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/DefaultModelRepository.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/DefaultModelResourceManager.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/ModelRepository.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/ModelResourceManager.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/ModelServerEditingDomain.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/watchers/ReconcilingStrategy.java
- tests/org.eclipse.emfcloud.modelserver.emf.tests/src/org/eclipse/emfcloud/modelserver/emf/common/watchers/FileModelWatcherIntegrationTest.java
A new configuration request triggers the initialize method of
ModelResourceManager.
Currently the known ResourceSets are simply cleared.
This is not enough as resources are still hold by the FileWatcher.
This is fixed now by unloading the resources.
Fix #192
> Add resource unload on configuration request

- bundles/org.eclipse.emfcloud.modelserver.common/src/org/eclipse/emfcloud/modelserver/common/patch/AbstractJsonPatchHelper.java
- Use DeleteCommand instead of RemoveCommand, when deleting an object (Remove from list and Unset feature still rely on RemoveCommand or SetCommand and won't modify cross-references)
fixes #207
> API V2: The patch operation "remove" doesn't remove cross references

- README.md
- bundles/org.eclipse.emfcloud.modelserver.client/src/org/eclipse/emfcloud/modelserver/client/ModelServerClientApiV2.java
- bundles/org.eclipse.emfcloud.modelserver.client/src/org/eclipse/emfcloud/modelserver/client/SubscriptionOptions.java
- bundles/org.eclipse.emfcloud.modelserver.client/src/org/eclipse/emfcloud/modelserver/client/XmiToEObjectSubscriptionListener.java
- bundles/org.eclipse.emfcloud.modelserver.client/src/org/eclipse/emfcloud/modelserver/client/v2/ModelServerClientV2.java
- bundles/org.eclipse.emfcloud.modelserver.client/src/org/eclipse/emfcloud/modelserver/internal/client/ModelServerClientDelegate.java
- bundles/org.eclipse.emfcloud.modelserver.common/src/org/eclipse/emfcloud/modelserver/common/ModelServerPathParametersV2.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/DefaultSessionController.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/ModelURIConverter.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/util/ContextRequest.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/util/JsonPatchHelper.java
- examples/org.eclipse.emfcloud.modelserver.example/src/main/java/org/eclipse/emfcloud/modelserver/example/client/ExampleModelServerClient.java
- tests/org.eclipse.emfcloud.modelserver.emf.tests/src/org/eclipse/emfcloud/modelserver/emf/common/DefaultSessionControllerTest.java
- tests/org.eclipse.emfcloud.modelserver.emf.tests/src/org/eclipse/emfcloud/modelserver/emf/util/JsonPatchHelperTest.java
- tests/org.eclipse.emfcloud.modelserver.tests/src/org/eclipse/emfcloud/modelserver/tests/util/MoreMatchers.java
As described in the feature request, add a new subscription parameter for `paths` scheme.
Now, with the `paths=uriFragments` query parameter in the `/api/v2/subscribe` request, the `Operation`s in JSON Patches provided by the server in incremental update notifications will have `path` properties of the form
`#_0uuid6017-fun/feature/3`
whereas otherwise they have the form
`/path/1/through/3/containment/0/references/7/to/0/a/1/feature/-`
Note that the resource URI is not included; only the fragment portion. A future enhancement can include resources URIs when they are necessary either to disambiguate operations on objects in different resources or when the resource URI is different to the `modeluri` parameter of the subscription. This is for now on par with the JSON Pointer scheme, which …
> API v2: Subscription option for URI fragments in update notifications

- pom.xml
- Revert examples directory exclusion for m2 deployment
- Deploy job can publish example modules without -DpluginsOnly argument
- Release job uses argument -DpluginsOnly to avoid publishing the example module
> #200 Follow-up - Revert examples module integration in deploy build

- Jenkinsfile
- bundles/org.eclipse.emfcloud.modelserver.edit/src/org/eclipse/emfcloud/modelserver/edit/util/CommandUtil.java
Fix the behavior of TransactionContext.close() by using a CompositeChangeDescription instead of merging instances of ChangeDescription.
> 212: API V2: IndexOutOfBoundsException when closing Transaction

- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/DefaultModelController.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/DefaultSessionController.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/DefaultTransactionController.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/ModelListener.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/util/ContextResponse.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/util/JsonPatchHelper.java
- examples/org.eclipse.emfcloud.modelserver.example/src/main/java/org/eclipse/emfcloud/modelserver/example/ExampleServerModule.java
- tests/org.eclipse.emfcloud.modelserver.emf.tests/src/org/eclipse/emfcloud/modelserver/emf/common/DefaultModelControllerTest.java
Change the return value of edit, undo and redo operations, to return one patch per modified resource, in addition to the main-resource patch.
Before:
```json
{
"type": "success",
"data": {
"message": "Model 'SuperBrewer3000.coffee' successfully updated",
"patch": [
{
"op": "remove",
"path": "/workflows/0/nodes"
}
]
}
}
```
After:
```json
{
"type": "success",
"data": {
"message": "Model 'SuperBrewer3000.coffee' successfully updated",
"patch": [
{
"op": "remove",
"path": "/workflows/0/nodes"
}
],
"allPatches": [
{
"modelUri": "file:/home/camille/Git/modelserver/examples/org.eclipse.emfcloud.modelserver.example/.temp/workspace/SuperBrewer3000.coffee",
"patch": [
{
"op": "remove",
"path": "/workflows/0/nodes"
}
]
}
]
}
}
```
Note that for the main resource, the patches are redundant. We could …
> GH-209: API V2: Return patches for each affected resource

- bundles/org.eclipse.emfcloud.modelserver.common/src/org/eclipse/emfcloud/modelserver/common/patch/AbstractJsonPatchHelper.java
- bundles/org.eclipse.emfcloud.modelserver.common/src/org/eclipse/emfcloud/modelserver/common/patch/PatchUtil.java
- Add the possibility to specify Json Patches via a list of "Model Patch" objects, referencing a modelUri and a Patch. This allows edition of multi-resource models, with one Json Patch per resource.
Signed-off-by: Camille Letavernier <cletavernier@eclipsesource.com>
> GH-159: API V2: Properly define and support multi-resources patches/operations

- bundles/org.eclipse.emfcloud.modelserver.common/src/org/eclipse/emfcloud/modelserver/common/patch/AbstractJsonPatchHelper.java
- Use distinct commands for single-valued and multi-valued references
Fixes #220
> 220: API V2: JsonPatchHelper doesn't properly handle 'add' operations for single-valued references

- bundles/org.eclipse.emfcloud.modelserver.lib/build.properties
Without the jars the bundle cannot be consumed by p2 correctly as a
ClassNotFoundException is thrown.
> Add missing jars in lib project

- bundles/org.eclipse.emfcloud.modelserver.common/src/org/eclipse/emfcloud/modelserver/common/patch/AbstractJsonPatchHelper.java
- Use Enumerator instead of EEnumLiteral
- Add missing return statement for Enum values
Fixes #225
> 225: Enum values are not properly initialized when creating a new element

- bundles/org.eclipse.emfcloud.modelserver.common/src/org/eclipse/emfcloud/modelserver/common/patch/AbstractJsonPatchHelper.java
Currently `add` patches for attributes only handle many
features correctly. For single attributes a `SetCommand`
should be used instead.
Signed-off-by: Eugen Neufeld <eneufeld@eclipsesource.com>
> Improve handling of `add` patches on attributes

- bundles/org.eclipse.emfcloud.modelserver.common/src/org/eclipse/emfcloud/modelserver/common/patch/AbstractJsonPatchHelper.java
Improve handling of remove patches without an index
but which have an container.
When retrieving settings from emf like paths, the code
should first check whether an object can be retrieved and
only then do some path checks.
This way paths containing only an object id won't fail.
> Improve handling for remove and setting retrieval

- bundles/org.eclipse.emfcloud.modelserver.common/src/org/eclipse/emfcloud/modelserver/common/patch/AbstractJsonPatchHelper.java
- tests/org.eclipse.emfcloud.modelserver.emf.tests/resources/Test1.ecore
- tests/org.eclipse.emfcloud.modelserver.emf.tests/resources/Test1.json
- tests/org.eclipse.emfcloud.modelserver.emf.tests/resources/aConcreteClass1.xmi
- tests/org.eclipse.emfcloud.modelserver.emf.tests/src/org/eclipse/emfcloud/modelserver/emf/util/JsonPatchHelperTest.java
- tests/org.eclipse.emfcloud.modelserver.tests/META-INF/MANIFEST.MF
- tests/org.eclipse.emfcloud.modelserver.tests/src/org/eclipse/emfcloud/modelserver/tests/util/EMFMatchers.java
Insert at the index given by the path when an index is specified, for both `EReference`s and `EAttribute`s.
Fixes #240
> 240: JSON Patch: Object not added at index specified in add op

- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/patch/EMFCommandHandler.java
- tests/org.eclipse.emfcloud.modelserver.emf.tests/src/org/eclipse/emfcloud/modelserver/emf/patch/EMFCommandHandlerTest.java
Use the model URI provided by the context to request the most appropriate codec.
Fixes #242
> 242: EMFCommandHandler requests codec for null model URI

- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/di/ProviderDefaults.java
Reusing the object mapper can lead to problems.
For example the validation dynamically adds the resource to allow for id mapping.
Hence, a new object mapper is needed each time as the resource might change.
> Do not reuse object mapper

- bundles/org.eclipse.emfcloud.modelserver.common/src/org/eclipse/emfcloud/modelserver/common/APIVersion.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/DefaultModelResourceManager.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/codecs/CodecsManager.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/codecs/DICodecsManager.java
- tests/org.eclipse.emfcloud.modelserver.emf.tests/src/org/eclipse/emfcloud/modelserver/emf/common/DefaultModelControllerTest.java
- tests/org.eclipse.emfcloud.modelserver.emf.tests/src/org/eclipse/emfcloud/modelserver/emf/common/codecs/DICodecsManagerTest.java
Use the model URI provided by the request or session context if it is available.
Incidentally fix problems found in the `DefaultModelResourceManager` while debugging the issue in my application:
- catching all throwables, including `Error`s
- NPE in attempt to load a non-existent resource because the resource set is `null`
Fixes #245
> 245: Codecs looked up by workspace URI

- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/DefaultModelSynchronizer.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/ModelSynchronizer.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/SingleThreadModelController.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/SingleThreadTransactionController.java
- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/di/DefaultModelServerModule.java
Extract the single-thread execution mechanism from the `SingleThreadModelController` and generalize it, rebuilding it on the Java `ExecutorService`, as an injectable `ModelSynchronizer` service that is now also used by a new `SingleThreadTransactionController`.
Bind the new `SingleThreadTransactionController` by default.
Fixes #250
> Concurrency conflicts between Transaction- and ModelController

- bundles/org.eclipse.emfcloud.modelserver.emf/src/org/eclipse/emfcloud/modelserver/emf/common/DefaultModelSynchronizer.java
- tests/org.eclipse.emfcloud.modelserver.emf.tests/src/org/eclipse/emfcloud/modelserver/emf/common/DefaultModelSynchronizerTest.java
Cover the case in which the client of the ModelSynchronizer makes re-entrant syncExec or syncCall invocations.
Fixes #250
> Fix deadlock on re-entrant sync calls

- bundles/org.eclipse.emfcloud.modelserver.edit/src/org/eclipse/emfcloud/modelserver/edit/command/SetCommandContribution.java
- tests/org.eclipse.emfcloud.modelserver.edit.tests/src/org/eclipse/emfcloud/modelserver/edit/EMFCommandCodecTest.java
Fixing SetCommandContribution:
enable usage of SetCommand on monovalued containment features.
Signed-off-by: vhemery <vincent.hemery@bonitasoft.com>
> With command edit API, use SetCommand on a containment feature (#257)

- releng/org.eclipse.emfcloud.modelserver.codecoverage/pom.xml
Report coverage correctly on verify phase with all test dependencies.
Does not implement the PR check suggested in [eneufeld's comment](https://github.com/eclipse-emfcloud/emfcloud-modelserver/issues/266#issuecomment-1386955405)
Fixes #266
> Add code coverage for jacoco.
